# Generated by Django 4.1.3 on 2022-12-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('cell_phone', models.CharField(blank=True, max_length=10, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Información de contacto para empresa',
                'verbose_name_plural': 'Informacion de contacto para empresas',
            },
        ),
        migrations.AlterModelOptions(
            name='companymodel',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='companymodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=150, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='twitter',
            field=models.CharField(blank=True, max_length=150, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='web_site',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='mision',
            field=models.TextField(blank=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='nit',
            field=models.CharField(max_length=20, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Visión'),
        ),
        migrations.CreateModel(
            name='GaleryCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companymodel')),
            ],
            options={
                'verbose_name': 'Galeria de la compañia',
                'verbose_name_plural': 'Galerias de las compañias',
            },
        ),
        migrations.CreateModel(
            name='CommentCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Comentarios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentarios de usuarios a empresas',
            },
        ),
        migrations.CreateModel(
            name='CategoryCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(max_length=450, verbose_name='Descripción')),
                ('companies', models.ManyToManyField(to='company.companymodel')),
            ],
            options={
                'verbose_name': 'Categoria de la empresa',
                'verbose_name_plural': 'Categorias de las empresas',
            },
        ),
    ]
