# Generated by Django 4.1.3 on 2022-12-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_contactcompanymodel_alter_companymodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='logo',
            field=models.FileField(blank=True, upload_to='logos'),
        ),
    ]
