# Generated by Django 4.1.3 on 2023-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companymodel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='twitter',
        ),
        migrations.AddField(
            model_name='companymodel',
            name='email_company',
            field=models.CharField(blank=True, max_length=150, verbose_name='Correo de la compañia'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Emprendimiento'),
        ),
    ]
