# Generated by Django 4.1.3 on 2023-01-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_citymodel_options_alter_countrymodel_options_and_more'),
        ('company', '0005_companymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.citymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.countrymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymodel',
            name='deparment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.deparmentmodel'),
            preserve_default=False,
        ),
    ]
