# Generated by Django 4.1.3 on 2022-12-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('TI', 'Tarjeta de identidad'), ('CC', 'cedula de ciudadania'), ('CE', 'Cedula de extrtanjeria'), ('OTHER', 'Otros')], max_length=10, verbose_name='Tipo de Documento')),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('first_names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('birthdate', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('civil_status', models.CharField(choices=[('SINGLE', 'Soltero'), ('MARRIED', 'Casado'), ('DIVORCED', 'Divorciado'), ('WIDOWED', 'Viudo'), ('OTHER', 'Otros')], max_length=20, verbose_name='Estado Civil')),
                ('gender', models.CharField(choices=[('F', 'femenino'), ('M', 'Masculino'), ('OTHER', 'Otros')], max_length=10, verbose_name='Genero')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numero de telefono')),
                ('email', models.CharField(max_length=50, verbose_name='Correo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
