# Generated by Django 4.1.3 on 2023-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profileusermodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileusermodel',
            name='document',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numero de Identificación'),
        ),
    ]
